version: "3.9"

services:
  server_api_1:
    build:
      context: .
    container_name: server_api_1
    command: uvicorn server_api:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - DOMAIN_NAME=poa
    networks:
      - fiat_net

  server_api_2:
    build:
      context: .
    container_name: server_api_2
    command: uvicorn server_api:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    environment:
      - DOMAIN_NAME=pucrs
    networks:
      - fiat_net

  user_api_1:
    build:
      context: .
    container_name: user_api_1
    command: bash -c "DOMAIN_NAME=poa.com SERVER_URL=http://server_api_1:8001 uvicorn user_api:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - DOMAIN_NAME=poa.com
      - SERVER_URL=http://server_api_1:8001
    networks:
      - fiat_net
    depends_on:
      - server_api_1

  user_api_2:
    build:
      context: .
    container_name: user_api_2
    command: bash -c "DOMAIN_NAME=pucrs.com SERVER_URL=http://server_api_2:8003 uvicorn user_api:app --host 0.0.0.0 --port 8002"
    ports:
      - "8002:8002"
    environment:
      - DOMAIN_NAME=pucrs.com
      - SERVER_URL=http://server_api_2:8003
    networks:
      - fiat_net
    depends_on:
      - server_api_2

networks:
  fiat_net:
    driver: bridge

